// order comment
import "reflect-metadata"
// order comment
import "@ant-design/v5-patch-for-react-19"
// order comment
import "../compositionRoot/styles/main.scss"
// order comment
import AntdProvider from "@/core/Antd/AntdProvider"
import QCProvider from "@/core/QueryClient/QCProvider"
import { AppLayout } from "@/layouts/AppLayout"
import { type ReactNode } from "react"
import "../../firebase"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="root">
        <AntdProvider>
          <QCProvider>
            <AppLayout>{children}</AppLayout>
          </QCProvider>
        </AntdProvider>
      </body>
    </html>
  )
}
